PREFIX vio: <http://vi.dbpedia.org/ontology/>
PREFIX rdfs: <http://www.w3.org/2000/01/rdf-schema#>

SELECT ?university ?universityName ?provinceName
WHERE {
  ?university a vio:University ;
              rdfs:label ?universityName ;
              vio:locatedInProvince ?province .
  ?province rdfs:label ?provinceName .
}
ORDER BY ?provinceName ?universityName
