PREFIX vio: <http://vi.dbpedia.org/ontology/>
PREFIX rdfs: <http://www.w3.org/2000/01/rdf-schema#>

SELECT ?university ?universityName ?year
WHERE {
  ?university a vio:University ;
              rdfs:label ?universityName ;
              vio:foundingYearOrg ?year .
}
ORDER BY ?year ?universityName
